### PR TITLE
Fixing NPE when listing alarm callback using nonexistent plugin.

### LINKED ISSUE #1152: Alarm callback using nonexistent plugin leads to NPE when listing alarm callbacks
Steps to reproduce:

1) Load alarm callback plugin
2) Create alarm callback using it
3) Unload plugin
4) Showing alarm callbacks for stream returns NPE

### PR DESCRIPTION
**Pull request by dennisoelkers**
This prevents an NPE when listing alarm callbacks if one of the
callbacks is using a now nonexistent plugin.
It was solved this way instead of filtering out nonexistent callback
types in the server to allow viewing/deleting those callbacks.

Fixes #1152

### CODE REVIEW

File: app/views/partials/alerts/list_alarm_callbacks.scala.html [hunk 1]
```diff
@@ -27,7 +27,11 @@
 
             <h3>
                 <i class="icon icon-ellipsis-vertical"></i>
-                @availableAlarmCallbacks.get(callback.getType).name
+                @if(availableAlarmCallbacks.get(callback.getType) != null) {
```
Comment (joschi) [inline app/views/partials/alerts/list_alarm_callbacks.scala.html]: Since I don't know the complexity of retrieving the alarm callbacks from the backend, I'd suggest putting `availableAlarmCallbacks.get(callback.getType)` into a variable as it's used again in the next conditional block.

Comment (kroepke) [inline app/views/partials/alerts/list_alarm_callbacks.scala.html]: In this case it's simply a hash, so that's fine. I'm not sure it's possible to store things in variables in scala templates, so this should be ok bug ugly.
